site_name: Imgfloat
site_description: Imgfloat User Documentation
site_url: https://docs.imgflo.at

theme:
  logo: assets/icon.png
  name: material
  highlightjs: true
  features:
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - toc.follow
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light mode

plugins:
  - search
  - social

markdown_extensions:
  - toc
  - markdown_include.include:
      base_path: .
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details

nav:
  - Home: index.md
  - Getting Started:
    - Broadcaster: 
      - Getting Started: tutorial/broadcaster/overview.md
      - OBS Setup: tutorial/broadcaster/obs.md
      - Integrations: tutorial/broadcaster/integrations.md
      - Audit Log: tutorial/broadcaster/audit_log.md
    - Channel Admin: 
      - Getting Started: tutorial/channel_admin/overview.md
  - Admin Console:
    - Overview: console/overview.md
    - Adding Your First Asset: console/first.md
    - Asset Types:
      - Images: console/assets/images.md
      - Videos and Gifs: console/assets/videos.md
      - Audio: console/assets/audio.md
      - Script Assets:
        - Overview: console/assets/scripts/overview.md
        - Example Script Asset: console/assets/scripts/example.md
        - Using Attachments: console/assets/scripts/attachments.md
        - Reading Chat: console/assets/scripts/chat.md
        - Drawing Emotes: console/assets/scripts/emotes.md
        - Dealing with errors: console/assets/scripts/errors.md
    - Marketplace: console/marketplace.md
